build:
  dependencies:
    override:
      - sudo apt-get update -y
      - sudo apt-get install -y git build-essential python valgrind
      - git submodule update --init --recursive
      - python ci-tools/install_cmake.py

  tests:
    override:
      - python ci-tools/run_ctest.py

checks:
    python:
        code_rating: true
        duplicate_code: true