language: c

matrix:
  include:
    - os: linux
      compiler: gcc-5
      dist: precise
      sudo: false
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-5', 'valgrind']
      install: python ci-tools/install_cmake.py   
      script: python ci-tools/run_ctest.py

    - os: linux
      compiler: clang-3.6
      dist: precise
      sudo: false
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
          packages: ['clang-3.6', 'llvm-3.6', 'valgrind']
      install: python ci-tools/install_cmake.py   
      script: python ci-tools/run_ctest.py

    - os: osx
      compiler: clang
      osx_image: xcode7.3
      install: ['brew update', 'brew install valgrind']
      install: python ci-tools/install_cmake.py   
      script: python ci-tools/run_ctest.py