version: 0.1.{build}

environment:
  matrix:
    - CTEST_CMAKE_GENERATOR: Visual Studio 15 2017
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - CTEST_CMAKE_GENERATOR: Visual Studio 15 2017 Win64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - CTEST_CMAKE_GENERATOR: Visual Studio 15 2017 ARM
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - CTEST_CMAKE_GENERATOR: Visual Studio 14 2015
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - CTEST_CMAKE_GENERATOR: Visual Studio 14 2015 Win64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - CTEST_CMAKE_GENERATOR: Visual Studio 14 2015 ARM
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - CTEST_CMAKE_GENERATOR: Visual Studio 12 2013
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    - CTEST_CMAKE_GENERATOR: Visual Studio 12 2013 Win64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    - CTEST_CMAKE_GENERATOR: Visual Studio 12 2013 ARM
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013

before_build:
  - cinst wget opencppcoverage
  - refreshenv

build_script:
  - git submodule update --init --recursive --quiet
  - python ci-tools/install_cmake.py
  - python ci-tools/run_ctest.py